### ISSUE TITLE
suppress types from test files

### ISSUE THREAD

**Issue by bsr203** [frairon/go-outline#39]
Hi,

thanks for this package. 

I could suppress test functions with the little icon on top, but all the types (struct,..) are listed along with the source file types. I typically don't want to see types for test tiles and may be a configurable option to suppress/ignore test files from outline parsing.

thanks.

**Comment by frairon** [comment]
Hi there! 
Thanks for the issue, you're totally right. I didn't think of that. 
Since the types in test files can be named like anything, I'd suggest to filter them by the filename pattern as you suggested in issue #40. So having file-based filters solves both issues, or am I missing something?

Cheers!

**Comment by bsr203** [comment]
yup. #40 address both. :-) thanks for the quick response.
